### ISSUE TITLE
The number of test images is inconsistent with the paper for some cases.

### ISSUE THREAD

**Issue by KeepRunning2023** [huynguyen792/AG-ReID.v2#1]
First of all, I would like to express my sincere appreciation for the meaningful contribution made by the authors. However, while analyzing the test data, I have encountered some inconsistencies with the information provided in the paper. Specifically, in the testing set of ''Aerial to CCTV'' , the paper states that there are 6374 CCTV images, whereas the actual dataset provided contains 6347 images. Similarly, in the testing set of  ''Wearable to Aerial'', the paper mentions 12256 Aerial images, while the provided dataset consists of 12568 Aerial images. I kindly request the authors to verify whether this is an error on my part or if there is a discrepancy in the data. Thanks.

**Comment by huynguyen792** [comment]
Thank you for bringing the discrepancy in the image counts to our attention. We have confirmed that there is indeed an inconsistency between the numbers reported in the paper and the actual dataset. We sincerely apologize for this oversight. We will issue a formal correction statement to the journal/conference and update the dataset repository to ensure the correct image counts are clearly stated. Please be assured that this error does not affect the overall methodology, results, or conclusions of our research. We appreciate your thorough review and feedback, which helps us maintain the highest standards of accuracy and transparency in our work.

**Comment by KeepRunning2023** [comment]
Thank you very much for your response and verification. Once again, I sincerely appreciate the authors' contribution to this work and dataset.
