### ISSUE TITLE
Issues about dataset division under Aerial camera

### ISSUE THREAD

**Issue by Vanxy999** [huynguyen792/AG-ReID.v2#3]
![image](https://github.com/user-attachments/assets/faa3368c-36da-475b-a173-32ae4f18aa07)

Thank you for your wonderful work. But the details about the division of query and gallery in the aerial view are not given, can you help me with this?

**Comment by kailashhambarde** [comment]
Hi,

Thank you for the update regarding the download issue. 
I appreciate the suggested workaround and will try downloading the files individually as advised.
If I encounter further issues, I will reach out.
